# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "gpt-chat-dev"
client_id = "787d25f0632d150cfd79c24ea4403b0f"
application_url = "https://band-brave-mf-thy.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://band-brave-mf-thy.trycloudflare.com/auth/callback",
  "https://band-brave-mf-thy.trycloudflare.com/auth/shopify/callback",
  "https://band-brave-mf-thy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9270ec0b.myshopify.com"
